/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CardCreateDto,
    CardCreateDtoFromJSON,
    CardCreateDtoToJSON,
} from '../models/CardCreateDto';
import {
    type CardResponseDto,
    CardResponseDtoFromJSON,
    CardResponseDtoToJSON,
} from '../models/CardResponseDto';
import {
    type PageCardResponseDto,
    PageCardResponseDtoFromJSON,
    PageCardResponseDtoToJSON,
} from '../models/PageCardResponseDto';
import {
    type TransferRequestDto,
    TransferRequestDtoFromJSON,
    TransferRequestDtoToJSON,
} from '../models/TransferRequestDto';

export interface CreateCardRequest {
    cardCreateDto: CardCreateDto;
}

export interface GetCardsByUserRequest {
    userId: string;
    page?: number;
    size?: number;
    sortBy?: string;
    direction?: GetCardsByUserDirectionEnum;
}

export interface TransferCardsRequest {
    transferRequestDto: TransferRequestDto;
}

/**
 * 
 */
export class CardControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCard without sending the request
     */
    async createCardRequestOpts(requestParameters: CreateCardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardCreateDto'] == null) {
            throw new runtime.RequiredError(
                'cardCreateDto',
                'Required parameter "cardCreateDto" was null or undefined when calling createCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/cards`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CardCreateDtoToJSON(requestParameters['cardCreateDto']),
        };
    }

    /**
     */
    async createCardRaw(requestParameters: CreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CardResponseDto>> {
        const requestOptions = await this.createCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async createCard(requestParameters: CreateCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CardResponseDto> {
        const response = await this.createCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCardsByUser without sending the request
     */
    async getCardsByUserRequestOpts(requestParameters: GetCardsByUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getCardsByUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/cards/user/{userId}`;
        urlPath = urlPath.replace('{userId}', encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getCardsByUserRaw(requestParameters: GetCardsByUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageCardResponseDto>> {
        const requestOptions = await this.getCardsByUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageCardResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getCardsByUser(requestParameters: GetCardsByUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageCardResponseDto> {
        const response = await this.getCardsByUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transferCards without sending the request
     */
    async transferCardsRequestOpts(requestParameters: TransferCardsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transferRequestDto'] == null) {
            throw new runtime.RequiredError(
                'transferRequestDto',
                'Required parameter "transferRequestDto" was null or undefined when calling transferCards().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/cards/transfer`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferRequestDtoToJSON(requestParameters['transferRequestDto']),
        };
    }

    /**
     */
    async transferCardsRaw(requestParameters: TransferCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.transferCardsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async transferCards(requestParameters: TransferCardsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferCardsRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const GetCardsByUserDirectionEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type GetCardsByUserDirectionEnum = typeof GetCardsByUserDirectionEnum[keyof typeof GetCardsByUserDirectionEnum];
