/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestDto
 */
export interface AuthRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRequestDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRequestDto
     */
    password: string;
}

/**
 * Check if a given object implements the AuthRequestDto interface.
 */
export function instanceOfAuthRequestDto(value: object): value is AuthRequestDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthRequestDtoFromJSON(json: any): AuthRequestDto {
    return AuthRequestDtoFromJSONTyped(json, false);
}

export function AuthRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthRequestDtoToJSON(json: any): AuthRequestDto {
    return AuthRequestDtoToJSONTyped(json, false);
}

export function AuthRequestDtoToJSONTyped(value?: AuthRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

