/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardResponseDto
 */
export interface CardResponseDto {
    /**
     * 
     * @type {string}
     * @memberof CardResponseDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CardResponseDto
     */
    maskedNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CardResponseDto
     */
    ownerName?: string;
    /**
     * 
     * @type {Date}
     * @memberof CardResponseDto
     */
    expiryDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CardResponseDto
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof CardResponseDto
     */
    balance?: number;
    /**
     * 
     * @type {Date}
     * @memberof CardResponseDto
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CardResponseDto interface.
 */
export function instanceOfCardResponseDto(value: object): value is CardResponseDto {
    return true;
}

export function CardResponseDtoFromJSON(json: any): CardResponseDto {
    return CardResponseDtoFromJSONTyped(json, false);
}

export function CardResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'maskedNumber': json['maskedNumber'] == null ? undefined : json['maskedNumber'],
        'ownerName': json['ownerName'] == null ? undefined : json['ownerName'],
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
        'status': json['status'] == null ? undefined : json['status'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CardResponseDtoToJSON(json: any): CardResponseDto {
    return CardResponseDtoToJSONTyped(json, false);
}

export function CardResponseDtoToJSONTyped(value?: CardResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'maskedNumber': value['maskedNumber'],
        'ownerName': value['ownerName'],
        'expiryDate': value['expiryDate'] == null ? value['expiryDate'] : value['expiryDate'].toISOString().substring(0,10),
        'status': value['status'],
        'balance': value['balance'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

