/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardCreateDto
 */
export interface CardCreateDto {
    /**
     * 
     * @type {string}
     * @memberof CardCreateDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CardCreateDto
     */
    cardNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CardCreateDto
     */
    ownerName: string;
    /**
     * 
     * @type {Date}
     * @memberof CardCreateDto
     */
    expiryDate: Date;
}

/**
 * Check if a given object implements the CardCreateDto interface.
 */
export function instanceOfCardCreateDto(value: object): value is CardCreateDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('cardNumber' in value) || value['cardNumber'] === undefined) return false;
    if (!('ownerName' in value) || value['ownerName'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    return true;
}

export function CardCreateDtoFromJSON(json: any): CardCreateDto {
    return CardCreateDtoFromJSONTyped(json, false);
}

export function CardCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'cardNumber': json['cardNumber'],
        'ownerName': json['ownerName'],
        'expiryDate': (new Date(json['expiryDate'])),
    };
}

export function CardCreateDtoToJSON(json: any): CardCreateDto {
    return CardCreateDtoToJSONTyped(json, false);
}

export function CardCreateDtoToJSONTyped(value?: CardCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'cardNumber': value['cardNumber'],
        'ownerName': value['ownerName'],
        'expiryDate': value['expiryDate'].toISOString().substring(0,10),
    };
}

