/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { CardResponseDto } from './CardResponseDto';
import {
    CardResponseDtoFromJSON,
    CardResponseDtoFromJSONTyped,
    CardResponseDtoToJSON,
    CardResponseDtoToJSONTyped,
} from './CardResponseDto';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageCardResponseDto
 */
export interface PageCardResponseDto {
    /**
     * 
     * @type {number}
     * @memberof PageCardResponseDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCardResponseDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageCardResponseDto
     */
    size?: number;
    /**
     * 
     * @type {Array<CardResponseDto>}
     * @memberof PageCardResponseDto
     */
    content?: Array<CardResponseDto>;
    /**
     * 
     * @type {number}
     * @memberof PageCardResponseDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageCardResponseDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {number}
     * @memberof PageCardResponseDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageCardResponseDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageCardResponseDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageCardResponseDto
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageCardResponseDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageCardResponseDto interface.
 */
export function instanceOfPageCardResponseDto(value: object): value is PageCardResponseDto {
    return true;
}

export function PageCardResponseDtoFromJSON(json: any): PageCardResponseDto {
    return PageCardResponseDtoFromJSONTyped(json, false);
}

export function PageCardResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageCardResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CardResponseDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageCardResponseDtoToJSON(json: any): PageCardResponseDto {
    return PageCardResponseDtoToJSONTyped(json, false);
}

export function PageCardResponseDtoToJSONTyped(value?: PageCardResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CardResponseDtoToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

