/* tslint:disable */
/* eslint-disable */
/**
 * Bank Cards API
 * REST API for bank card management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferRequestDto
 */
export interface TransferRequestDto {
    /**
     * 
     * @type {string}
     * @memberof TransferRequestDto
     */
    fromCardId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferRequestDto
     */
    toCardId: string;
    /**
     * 
     * @type {number}
     * @memberof TransferRequestDto
     */
    amount: number;
}

/**
 * Check if a given object implements the TransferRequestDto interface.
 */
export function instanceOfTransferRequestDto(value: object): value is TransferRequestDto {
    if (!('fromCardId' in value) || value['fromCardId'] === undefined) return false;
    if (!('toCardId' in value) || value['toCardId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransferRequestDtoFromJSON(json: any): TransferRequestDto {
    return TransferRequestDtoFromJSONTyped(json, false);
}

export function TransferRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'fromCardId': json['fromCardId'],
        'toCardId': json['toCardId'],
        'amount': json['amount'],
    };
}

export function TransferRequestDtoToJSON(json: any): TransferRequestDto {
    return TransferRequestDtoToJSONTyped(json, false);
}

export function TransferRequestDtoToJSONTyped(value?: TransferRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromCardId': value['fromCardId'],
        'toCardId': value['toCardId'],
        'amount': value['amount'],
    };
}

